#设置Tomcat端口，默认8080
server.port: 8080
#设置Tomcat编码
server.tomcat.uri-encoding: UTF-8
#开发时关闭缓存,不然没法看到实时页面
spring.thymeleaf.cache: false

#数据库配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://8.130.38.30:3306/questionnaire?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&currentSchema=db_user
      username: root
      password: 20021229.bin

#配置模型路径
mybatis.type-aliases-package: com/neu/group/dao

#日志
logging:
  level:
    root: info
